project:
  type: website

website:
  title: ""
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: work.qmd
        text: Work
      - href: ideas.qmd
        text: Ideas
    right: 
      - icon: "film"
      - icon: "youtube"
      - icon: "linkedin"
      - icon: "instagram"
      - icon: "github"
      - icon: "binoculars-fill"
format:
  html:
    css: mystyle.css
