project:
  type: website

website:
  title: ""
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: work.qmd
        text: Work
      - href: ideas.qmd
        text: Ideas
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/francesco-rosadini-6090891b9/
      - icon: film
        href: https://letterboxd.com/Francesco_Rosa/
      - icon: github
        href: https://github.com/francescorosa01
      - icon: binoculars-fill
        href: https://www.inaturalist.org/people/francescorosadini
format:
  html:
    css: mystyle.css
