project:
  type: website

website:
  title: "Francesco Rosadini"
  site-url: https://francescorosadini.github.io/
  navbar: 
    left:
      - href: "#home"
        text: Home
      - href: "#about"
        text: About
      - href: "#work"
        text: Work
      - href: "#ideas"
        text: Ideas
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/francesco-rosadini-6090891b9/
      - icon: film
        href: https://letterboxd.com/Francesco_Rosa/
      - icon: github
        href: https://github.com/francescorosa01
      - icon: binoculars-fill
        href: https://www.inaturalist.org/people/francescorosadini
format:
  html:
    css: mystyle.css
    smooth-scroll: true
